name: jmas_desktop
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.2.2 #WEB
  shared_preferences: ^2.3.3 #Guardar token
  intl: ^0.19.0 #Fecha
  pdf: ^3.11.1 #PDF
  printing: ^5.13.4 #Imprimir
  path_provider: ^2.1.5 #Archivos sistema
  file_picker: ^8.1.6 #Seleccionar carpeta
  image_picker: ^1.1.2 #Seleccionar imagen   
  bitsdojo_window: ^0.1.0 #Tamaño pantaña
  qr_flutter: ^4.1.0 #QR
  flutter_svg: ^2.0.17 #SVG
  excel: ^4.0.6
  universal_html: ^2.2.4
  open_file: ^3.5.10
  syncfusion_flutter_xlsio: ^29.2.11

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/sinFoto.jpg
    - assets/icons/
    - assets/images/logo_jmas_sf.png
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700